# fly.toml app configuration file generated for leethub on 2025-05-31T15:28:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leethub'
primary_region = 'sin'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
